import './globals.css';
import { Inter } from 'next/font/google';
import { ChakraProviders } from './ChakraProviders';
import SidebarWithHeader from './components/Sidebar';
import { ColorModeScript } from '@chakra-ui/react';
import theme from './theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' data-theme={'corporate'}>
      <body className={inter.className}>
        <ChakraProviders>
          <SidebarWithHeader>{children}</SidebarWithHeader>
        </ChakraProviders>
      </body>
    </html>
  );
}
