import '../globals.css';
import { Inter } from 'next/font/google';
import { ChakraProviders } from '../ChakraProviders';
import SidebarWithHeader from '../components/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ChakraProviders>
      <SidebarWithHeader>{children}</SidebarWithHeader>
    </ChakraProviders>
  );
}
